export enum ChangeTypeEnum {
    ADD_PASSWORD = 'ADD_PASSWORD',
    DELETE_PASSWORD = 'DELETE_PASSWORD',
    MODIFY_PASSWORD = 'MODIFY_PASSWORD',
    SHOW_PASSWORD = 'SHOW_PASSWORD',
    SHARE_PASSWORD = 'SHARE_PASSWORD',
    RESTORE_STATE = 'RESTORE_STATE',
  }